version: '3.8'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file: .env
    restart: on-failure
    volumes:
      - mariadb_vol:/var/lib/mysql/
    healthcheck: 
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/tgrasset/data/mariadb'

  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tgrasset/data/wordpress'
